### ISSUE TITLE
Major security flaw...

### ISSUE THREAD

**Issue by benbroce** [benbroce3/PiCamServer#5]
Typing in "[IP]/picstream.php" takes you straight to picstream, no password required...

Fix (for now) by storing a cookie with the password when entered correctly, and putting a php conditional that checks for the correct value at the beginning of picstream, vidstream, and config (which we'll make today).

**Comment by TechnoScientist** [comment]
Hey Ben I fixed the security flaw, at least it should work I haven't tested
it yet.You can check it out on github

**Comment by benbroce** [comment]
Fixed by TechnoScientist on 5/23/16.
